api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
# src/Example/PizzaBundle/Resources/config/routing.yml
bars:
    resource: "@ApiBundle/Controller/ApiController.php"
    prefix: /api/
    type: rest    
